#!/bin/sh
# Copyright (C) 2011 O.S. Systems Software LTDA.
# Licensed on MIT

psplash_finish_enabled() {
    return 0
}

psplash_finish_run() {
    mkdir -p $ROOTFS_DIR/run
    mount --move /run $ROOTFS_DIR/run
}
