#!/bin/sh
# Copyright (C) 2017 O.S. Systems Software LTDA.
# Licensed on MIT

psplash_enabled() {
    if [ ! -e /dev/fb0 ]; then
        echo "Framebuffer /dev/fb0 not detected"
        echo "Boot splashscreen disabled"
        exit 0;
    fi

    read CMDLINE < /proc/cmdline
    for x in $CMDLINE; do
        case $x in
            psplash=false)
                echo "Boot splashscreen disabled"
                exit 0;
                ;;
        esac
    done
}

psplash_run() {
    mkdir -p /run
    if ! mountpoint -q /run; then
        mount tmpfs -t tmpfs /run
    fi

    rotation=0
    if [ -e /etc/rotation ]; then
        read rotation < /etc/rotation
    fi

    /usr/bin/psplash --angle $rotation &
}
